services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    hostname: broker
    ports:
      - 29092:29092   # puerto para clientes
      - 29093:29093   # puerto interno del controller
    environment:
      # Identidad y roles
      KAFKA_BROKER_ID: 1
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # Quorum (para un solo nodo)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093

      # Logs y replicaci√≥n
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # Opcional: cluster id predefinido
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 29092 || exit 1"]
      interval: 5s
      retries: 10


  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: "broker:29092"
      CONNECT_URL: "http://kafka-connect:8083"
    depends_on:
      - broker
      - kafka-connect

  
  kafka-connect:
    build:
      context: ./kafka_connect
      dockerfile: Dockerfile
    container_name: kafka-connect
    hostname: kafka-connect

    depends_on:
      broker:
        condition: service_healthy


    ports:
      - "8083:8083"
    volumes:
      - ./kafka_connect/plugins:/usr/share/kafka/plugins